ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS opens INTEGER DEFAULT 0;
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS clicks INTEGER DEFAULT 0;
ALTER TABLE subscribers ADD COLUMN IF NOT EXISTS unsubscribed_reason VARCHAR(30);
